### PR TITLE
Bug/459- Text overflow issues

### LINKED ISSUE #459: Text Overflow Issue
In some cases Android incorrectly measures the size of the text field resulting in the last line being cut off.

### PR DESCRIPTION
**Pull request by samwoodall**
### Description

Multiline text views with StyleSpans on devices running android 10 always use the wrong line ascent, even if line spacing is explicitly set, putting the baseline in the wrong position. 
The reason for this is that on android 10 the ascent initialization expression in StaticLayout.java results in a different value when a span is applied.

For context (from Paint.java) ascent is 

> The recommended distance above the baseline for singled spaced text. 

Ln 856 of StaticLayout.java in android-29 sdk sources
```
final int ascent = fallbackLineSpacing
        ? Math.min(fmAscent, Math.round(ascents[breakIndex]))
        : fmAscent;
```

`fmAscent` result in the same value on all android versions, and the correct value (as bolding the typefaces we use shouldn’t change the overall vertical space). Only `Math.round(ascents[breakIndex])` differs between versions (using the wrong height).

Disabling fallbackLineSpacing for android 10+ should provide us with correct line spacing for latin alphabet languages.

Before sdk 28 there is no fallback like spacing in StaticLayout.java.

### Screenshots 
**Before**
Screenshot_20200401-101242

**After**, Note: Here the left column of text is misaligned with the center and right columns, this is because the original experience uses different top margins for the left column.

Screenshot_20200401-101529

### Related issues
closes #459

### CODE REVIEW

**Comment by orospakr** [comment]
@samwoodall is there an upstream bug filed for this?

File: sdk/src/main/kotlin/io/rover/sdk/ui/blocks/concerns/text/ViewText.kt [hunk 1]
```diff
@@ -24,6 +24,11 @@ internal class ViewText(
         // worry, the ascenders do not appear to be clipped either).
         textView.includeFontPadding = false
 
+        // This is set to prevent the wrong line spacing being used on android 10+ when StyleSpans are applied
+        if (Build.VERSION.SDK_INT >= 29) {
```
Comment (orospakr) [inline sdk/src/main/kotlin/io/rover/sdk/ui/blocks/concerns/text/ViewText.kt:28]: if there is an upstream bug filed for this, then this workaround may not appropriate for versions after 29.

**Comment by samwoodall** [comment]
@orospakr No, I can't see one, I'll file one. I think there has to be a bug somewhere, unless whatever changed that for 29 is actually a fix for incorrect behaviour in 28

**Review by orospakr — APPROVED** [review]
