### PR TITLE
Bug/399 - Remove option views before adding new option views

### LINKED ISSUE #399: Fix potential for Image Poll and Text Poll option rebinding issues

### PR DESCRIPTION
**Pull request by samwoodall**
## Description
Remove option views before adding new option views. Keep option views in ordered list in order to be able to access views directly

closes #399

### CODE REVIEW

File: sdk/src/main/kotlin/io/rover/sdk/ui/blocks/poll/ViewTextPoll.kt [hunk 1]
```diff
@@ -27,7 +27,7 @@ internal class ViewTextPoll(override val view: LinearLayout) : ViewTextPollInter
         )
     }
 
-    private lateinit var optionViews: List<TextOptionView>
+    private val optionViews = mutableListOf<TextOptionView>()
```
Comment (orospakr) [inline sdk/src/main/kotlin/io/rover/sdk/ui/blocks/poll/ViewTextPoll.kt]: Why not just set the option views as an immutable list?  I notice that you're doing extra work to allow for views to be added to this list from multiple places and yet you're just setting it in setupOptionViews().

Ditto for the image poll side of things.

**Review by orospakr — CHANGES_REQUESTED** [review]

**Review by orospakr — APPROVED** [review]
